---
title: "刑法助教課"
author: "董宸賓"
date: "2023-10-25"
description: |
  
output:
  distill::distill_article: 
   toc: False
   theme: "css1.css"
main-color: "#0F2E3D"
---

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

## 論法益：刑230血親性交罪

### 開頭

- 說明主旨：刑法之犯罪應以有可罰行為前提

一、按刑法之犯罪，乃以行為人之行為侵害法益為前提，國家亦僅得就侵害法益之行為處罰。是若行為並為侵害任何法義者，自不應…

### 中段

- 首先引入法條

- 列舉說明其可能之法益

- 最後分述對法益之質疑

二、次按，刑230規定。參酌本體立法理由，可知優生學、善良風俗<br>
亦有學者認為婚姻、性自主<br>
惟此種法益是否正當險有疑問，以下分述之<br>
(一)優生<br>
  1.依立法理由->基因突變/保障胎兒之健康<br>
  2.惟1.性交之定義2.遺傳疾病及不得生育，顯非<br>
(二)善良風俗<br>
…<br>
(三)性自主<br>
  1.本說認為<br>
  2.惟1.合意性交2.妨害風化罪章<br>
(四)婚姻家庭<br>
  1.本說認為<br>
  2.惟1.因果2.相互扶持<br>

### 結論

- 闡明論點

三、綜上，以前開四者作為法益，其正當性均有疑問，學生認為於本條並不存在保護法益之情形，即無應罰性。


## 適用範圍

### 題目：

 台灣人甲於休假期間欲搭機出遊；其於桃園機場登上註冊為韓國之飛機。登機後起飛<br>
前，一名美國籍乘客乙因故與他人起爭執，一氣之下出拳毆打，甲見狀前往勸阻卻因此<br>
受到波及，造成右眼腫脹、手臂、小腿均有擦挫傷。乙遭逮捕後，甲欲對其提出刑法第<br>
277 條 1 項傷害罪告訴；查韓國刑法就傷害行為亦有論處。<br>
(一)、試問乙是否有我國刑法之適用？<br>
(二)、倘本案在飛機起飛並飛離我國領空後方發生，乙是否有我國刑法之適用？


### 開頭：開門見山的闡明論點

一、甲之行為成立354、278

### 中段：分法條論述

二、甲之重傷害罪卻仍有我國刑法之適用<br>
  1.本案查甲在韓國犯罪＝>無刑法第3條之屬地原則之適用<br>
  2.次按第7條（引法條）之規定，查甲係我國國民且係在領域外犯罪，已如前　                 述，又甲所犯之354、278均屬刑5、6以外之犯罪。然刑354最輕本刑...自無刑法第7條適用。
  至就278最輕本刑在3年以上，且依題示行為地法律亦有處罰。<br>
  
### 結論：再次闡明論點

三、重傷有處罰，毀損則無。


### [刑法毀損罪(352、353、354)](https://law.moj.gov.tw/LawClass/LawSingleRela.aspx?PCODE=C0000001&FLNO=354&ty=L)

> 刑法毀損罪(352、353、354)<br>
刑§352：毀棄、損壞他人文書或致令不堪用，足以生損害於公眾或他人者，處三年以下有期徒刑、拘役或三萬元以下罰金。<br>
刑§353：<br>
1.毀壞他人建築物、礦坑、船艦或致令不堪用者，處六月以上五年以下有期徒刑。<br>
2.因而致人於死者，處無期徒刑或七年以上有期徒刑，致重傷者，處三年以上十年以下有期徒刑。<br>
3.第一項之未遂犯罰之。<br>
刑§354：毀棄、損壞前二條以外之他人之物或致令不堪用，足以生損害於公眾或他人者，處二年以下有期徒刑、拘役或一萬五千元以下罰金。


### [刑法普通傷害罪()]

傷害人之身體或健康者，處五年以下有期徒刑、拘役或五十萬元以下罰金。
犯前項之罪，因而致人於死者，處無期徒刑或七年以上有期徒刑；致重傷者，處三年以上十年以下有期徒刑。
